# @package _global_

defaults:
  - _self_
  - datamodule: libri.yaml
  - model: advance.yaml
  - path: server.yaml
  - trainer: default.yaml

name: 'cnn_embedding_clipping'
device: 'cuda:0'
seed: 1004

DEBUG: False

# learning
resume: False
epoch: 100
es_patience: 0 # if es_patient == 0, do not early stop.
mixed_precision: True

# set in codes
dt_string: None
len_train_loader: None